### ISSUE TITLE
With target level 9 in Eclipse: java.lang.UnsupportedClassVersionError: org/eclipse/jdt/internal/compiler/apt/model/ModuleElementImpl

### ISSUE THREAD

**Issue by stefanocke** [japkit/japkit#35]
- Eclipse Photon
- runs on JDK 8
- Japkit Examples upgraded to source and target level 9
- JDK 10 and 11 installed in Eclipse

```
Caused by: java.lang.UnsupportedClassVersionError: org/eclipse/jdt/internal/compiler/apt/model/ModuleElementImpl
	at org.eclipse.jdt.internal.compiler.apt.model.PackageElementImpl.getEnclosingElement(PackageElementImpl.java:117)
	at de.japkit.rules.LibraryRule.nextEnclosingTypeElementWithLibraryAnnotation(LibraryRule.java:172)
	at de.japkit.rules.LibraryRule.nextEnclosingTypeElementWithLibraryAnnotation(LibraryRule.java:176)
```

As far as I understand, the JDK8 which runs Eclipse does not like to load ModuleElementImpl which ist for Java 9+
That can be avoided, since we don't need the module anyway.

**Comment by stefanocke** [comment]
The exception above is fixed now, but in Eclipse, there are errors like this now:

Cannot determine qualified name for error type jdk.Profile+Annotation

**Comment by stefanocke** [comment]
In Maven, target level 9 + JDT does not work either (at least with jdk 10):

```
java.lang.NullPointerException
	at org.eclipse.jdt.internal.compiler.lookup.BinaryModuleBinding.create(BinaryModuleBinding.java:64)
	at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.getModuleFromAnswer(LookupEnvironment.java:427)
```

**Comment by stefanocke** [comment]
The Maven issue will be considered in a diffrent bug.
The original exception has been fixed.
The strange "Cannot determine qualified name for error type jdk.Profile+Annotation" did not occure anymore.
