### ISSUE TITLE
javax/lang/model/element/RecordComponentElement has been compiled by a more recent version of the Java Runtime (class file version 58.0), this version of the Java Runtime only recognizes class file versions up to 55.0

### ISSUE THREAD

**Issue by stefanocke** [japkit/japkit#57]
With Eclipse 2020-06, running on a JDK < 14 , the following Exception occurs for all japkit-example projects.
When running on JDK 14, it disappears.

The exception does not depend on the JDK version of the example project.

TODO: File an Eclipse bug (?).

```
java.lang.Exception: java.lang.UnsupportedClassVersionError: javax/lang/model/element/RecordComponentElement has been compiled by a more recent version of the Java Runtime (class file version 58.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:172)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:124)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:171)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:138)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotationsInternal(Compiler.java:958)
	at org.eclipse.jdt.internal.compiler.Compiler.processAnnotations(Compiler.java:932)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:450)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:426)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:386)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.compile(BatchImageBuilder.java:214)
	at org.eclipse.jdt.internal.core.builder.AbstractImageBuilder.compile(AbstractImageBuilder.java:318)
	at org.eclipse.jdt.internal.core.builder.BatchImageBuilder.build(BatchImageBuilder.java:79)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.buildAll(JavaBuilder.java:275)
	at org.eclipse.jdt.internal.core.builder.JavaBuilder.build(JavaBuilder.java:187)
	at org.eclipse.core.internal.events.BuildManager$2.run(BuildManager.java:832)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:220)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:263)
	at org.eclipse.core.internal.events.BuildManager$1.run(BuildManager.java:316)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.core.internal.events.BuildManager.basicBuild(BuildManager.java:319)
	at org.eclipse.core.internal.events.BuildManager.basicBuildLoop(BuildManager.java:371)
	at org.eclipse.core.internal.events.BuildManager.build(BuildManager.java:392)
	at org.eclipse.core.internal.events.AutoBuildJob.doBuild(AutoBuildJob.java:154)
	at org.eclipse.core.internal.events.AutoBuildJob.run(AutoBuildJob.java:244)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: java.lang.UnsupportedClassVersionError: javax/lang/model/element/RecordComponentElement has been compiled by a more recent version of the Java Runtime (class file version 58.0), this version of the Java Runtime only recognizes class file versions up to 55.0
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.defineClass(ModuleClassLoader.java:294)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.defineClass(ClasspathManager.java:717)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findClassImpl(ClasspathManager.java:640)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:608)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClassImpl(ClasspathManager.java:595)
	at org.eclipse.osgi.internal.loader.classpath.ClasspathManager.findLocalClass(ClasspathManager.java:567)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.findLocalClass(ModuleClassLoader.java:346)
	at org.eclipse.osgi.internal.loader.BundleLoader.findLocalClass(BundleLoader.java:398)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:477)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	at java.base/sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at java.base/sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at java.base/sun.reflect.generics.reflectiveObjects.LazyReflectiveObjectGenerator.reifyBounds(LazyReflectiveObjectGenerator.java:65)
	at java.base/sun.reflect.generics.reflectiveObjects.WildcardTypeImpl.getUpperBounds(WildcardTypeImpl.java:105)
	at java.base/sun.reflect.generics.reflectiveObjects.WildcardTypeImpl.toString(WildcardTypeImpl.java:150)
	at java.base/java.lang.reflect.Type.getTypeName(Type.java:46)
	at java.base/sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl.toString(ParameterizedTypeImpl.java:229)
	at java.base/java.lang.reflect.Type.getTypeName(Type.java:46)
	at java.base/java.lang.reflect.Method.specificToGenericStringHeader(Method.java:487)
	at java.base/java.lang.reflect.Executable.sharedToGenericString(Executable.java:153)
	at java.base/java.lang.reflect.Method.toGenericString(Method.java:481)
	at java.desktop/java.beans.MethodRef.set(MethodRef.java:46)
	at java.desktop/java.beans.MethodDescriptor.setMethod(MethodDescriptor.java:119)
	at java.desktop/java.beans.MethodDescriptor.<init>(MethodDescriptor.java:74)
	at java.desktop/java.beans.MethodDescriptor.<init>(MethodDescriptor.java:58)
	at java.desktop/java.beans.Introspector.getTargetMethodInfo(Introspector.java:1047)
	at java.desktop/java.beans.Introspector.getBeanInfo(Introspector.java:462)
	at java.desktop/java.beans.Introspector.getBeanInfo(Introspector.java:205)
	at javax.el.BeanELResolver$BeanProperties.<init>(BeanELResolver.java:221)
	at javax.el.BeanELResolver.property(BeanELResolver.java:343)
	at javax.el.BeanELResolver.getValue(BeanELResolver.java:92)
	at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:62)
	at javax.el.CompositeELResolver.getValue(CompositeELResolver.java:62)
	at de.japkit.el.javael3.JapkitELResolver.getValue(JapkitELResolver.java:88)
	at org.apache.el.parser.AstValue.getValue(AstValue.java:169)
	at org.apache.el.parser.AstDeferredExpression.getValue(AstDeferredExpression.java:43)
	at org.apache.el.parser.AstCompositeExpression.getValue(AstCompositeExpression.java:49)
	at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:190)
	at de.japkit.el.javael3.JavaEL3Provider.eval(JavaEL3Provider.java:36)
	at de.japkit.el.ELSupport.eval(ELSupport.java:329)
	at de.japkit.el.ELSupport.eval(ELSupport.java:227)
	at de.japkit.el.ELSupport.eval(ELSupport.java:221)
	at de.japkit.rules.RuleUtils.lambda$createNameExprRule$18(RuleUtils.java:548)
	at de.japkit.rules.MemberRuleSupport.createMember(MemberRuleSupport.java:324)
	at de.japkit.rules.MemberRuleSupport.lambda$null$7(MemberRuleSupport.java:248)
	at de.japkit.rules.ScopeRule.lambda$doInScope$3(ScopeRule.java:216)
	at de.japkit.el.ELSupport.scope(ELSupport.java:129)
	at de.japkit.rules.ScopeRule.doInScope(ScopeRule.java:220)
	at de.japkit.rules.ScopeRule.lambda$apply$0(ScopeRule.java:149)
	at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:783)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.common.collect.Iterators.addAll(Iterators.java:356)
	at com.google.common.collect.Lists.newArrayList(Lists.java:143)
	at com.google.common.collect.Lists.newArrayList(Lists.java:130)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.toList(IterableExtensions.java:620)
	at de.japkit.rules.ScopeRule.apply(ScopeRule.java:151)
	at de.japkit.rules.ScopeRule.apply(ScopeRule.java:114)
	at de.japkit.rules.ScopeRule.apply(ScopeRule.java:37)
	at de.japkit.rules.MemberRuleSupport.lambda$apply$9(MemberRuleSupport.java:268)
	at de.japkit.rules.AbstractRule.lambda$inRule$0(AbstractRule.java:67)
	at de.japkit.rules.RuleUtils.handleException(RuleUtils.java:1078)
	at de.japkit.rules.AbstractRule.inRule(AbstractRule.java:71)
	at de.japkit.rules.MemberRuleSupport.apply(MemberRuleSupport.java:305)
	at de.japkit.rules.MemberRuleSupport.apply(MemberRuleSupport.java:32)
	at de.japkit.rules.TemplateRule.lambda$null$5(TemplateRule.java:276)
	at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
	at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:612)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.common.collect.Iterators$ConcatenatedIterator.hasNext(Iterators.java:1330)
	at com.google.common.collect.Iterators.addAll(Iterators.java:355)
	at com.google.common.collect.Lists.newArrayList(Lists.java:143)
	at com.google.common.collect.Lists.newArrayList(Lists.java:130)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.toList(IterableExtensions.java:620)
	at de.japkit.rules.TemplateRule.lambda$null$6(TemplateRule.java:278)
	at de.japkit.rules.ScopeRule.lambda$doInScope$3(ScopeRule.java:216)
	at de.japkit.el.ELSupport.scope(ELSupport.java:129)
	at de.japkit.rules.ScopeRule.doInScope(ScopeRule.java:220)
	at de.japkit.rules.ScopeRule.apply(ScopeRule.java:155)
	at de.japkit.rules.ScopeRule.apply(ScopeRule.java:114)
	at de.japkit.rules.ScopeRule.apply(ScopeRule.java:37)
	at de.japkit.rules.TemplateRule.lambda$apply$7(TemplateRule.java:282)
	at de.japkit.rules.AbstractRule.lambda$inRule$0(AbstractRule.java:67)
	at de.japkit.rules.RuleUtils.handleException(RuleUtils.java:1078)
	at de.japkit.rules.AbstractRule.inRule(AbstractRule.java:71)
	at de.japkit.rules.TemplateRule.apply(TemplateRule.java:286)
	at de.japkit.rules.ClassRule.lambda$null$9(ClassRule.java:288)
	at de.japkit.rules.ScopeRule.lambda$doInScope$3(ScopeRule.java:216)
	at de.japkit.el.ELSupport.scope(ELSupport.java:129)
	at de.japkit.rules.ScopeRule.doInScope(ScopeRule.java:220)
	at de.japkit.rules.ScopeRule.apply(ScopeRule.java:155)
	at de.japkit.rules.ClassRule.lambda$generateClass$10(ClassRule.java:328)
	at de.japkit.rules.AbstractRule.lambda$inRule$0(AbstractRule.java:67)
	at de.japkit.rules.RuleUtils.handleException(RuleUtils.java:1078)
	at de.japkit.rules.AbstractRule.inRule(AbstractRule.java:71)
	at de.japkit.rules.ClassRule.generateClass(ClassRule.java:332)
	at de.japkit.rules.TriggerAnnotationRule.lambda$null$7(TriggerAnnotationRule.java:135)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at de.japkit.rules.TriggerAnnotationRule.lambda$null$9(TriggerAnnotationRule.java:137)
	at de.japkit.el.ELSupport.scope(ELSupport.java:129)
	at de.japkit.rules.TriggerAnnotationRule.lambda$processTriggerAnnotation$10(TriggerAnnotationRule.java:154)
	at de.japkit.rules.AbstractRule.lambda$inRule$0(AbstractRule.java:67)
	at de.japkit.rules.RuleUtils.handleException(RuleUtils.java:1078)
	at de.japkit.rules.AbstractRule.inRule(AbstractRule.java:71)
	at de.japkit.rules.TriggerAnnotationRule.processTriggerAnnotation(TriggerAnnotationRule.java:156)
	at de.japkit.processor.JapkitProcessor.lambda$processTriggerAnnotations$77(JapkitProcessor.java:926)
	at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
	at com.google.common.collect.Iterators$6.transform(Iterators.java:783)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at com.google.common.collect.Iterators$ConcatenatedIterator.hasNext(Iterators.java:1330)
	at com.google.common.collect.Iterators.addAll(Iterators.java:355)
	at com.google.common.collect.Iterables.addAll(Iterables.java:320)
	at com.google.common.collect.Sets.newLinkedHashSet(Sets.java:365)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.toSet(IterableExtensions.java:639)
	at de.japkit.processor.JapkitProcessor.processTriggerAnnotations(JapkitProcessor.java:938)
	at de.japkit.processor.JapkitProcessor.processAnnotatedClass(JapkitProcessor.java:860)
	at de.japkit.processor.JapkitProcessor.lambda$null$57(JapkitProcessor.java:699)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at de.japkit.processor.JapkitProcessor.lambda$processClassesAndWriteTypeElements$58(JapkitProcessor.java:702)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at de.japkit.processor.JapkitProcessor.processClassesAndWriteTypeElements(JapkitProcessor.java:704)
	at de.japkit.processor.JapkitProcessor.processLayerAsFarAsPossible(JapkitProcessor.java:492)
	at de.japkit.processor.JapkitProcessor.process(JapkitProcessor.java:254)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:142)
	... 25 more

```

**Comment by stefanocke** [comment]
What happens is:

- Java EL 3 creates an Introspector to introspect TypeElement.
- During this, it visits the new JDK 14 method TypeElementImpl org.eclipse.jdt.internal.compiler.apt.model.TypeElementImpl.getRecordComponents()
- When visiting its return type it tries to load RecordComponentElement

**Comment by stefanocke** [comment]
I guess this only happens by the introspection or if someone actually calls getRecordComponents().
So "ordinary" annotation processors will never have this issue.
I could construct a minimal test case where I actually use Introspector but I have my doubts this will be convincing enough that Eclipse will provide several implementations for TypeElementImpl.

Another question: Why do the jdt builds not fail yet?

**Comment by stefanocke** [comment]
Reproduced in Maven build with ecj >= 3.22.0

**Comment by stefanocke** [comment]
Solved by patching BenElResolver for Java EL 3.
This patch is not provided for juel. Please migrate to Java EL3 or run Eclipse with JDK 14.

Migration to Java EL3 should be a drop-in replacement. Just use japkit-all-javael3 or japkit-all-nogroovy dependency instead of japkit-all.
