### ISSUE TITLE
ECJ with -release option:  NPE or Cannot determine qualified name for error type jdk.Profile+Annotation Missing type: jdk.Profile+Annotation

### ISSUE THREAD

**Issue by stefanocke** [japkit/japkit#59]
Wenn setting <maven.compiler.release>, the ECJ / JDT buids fail.

Sometimes with:

 java.lang.Exception: java.lang.NullPointerException at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:172)

And sometimes with:

 Cannot determine qualified name for error type jdk.Profile+Annotation Missing type: jdk.Profile+Annotation

**Comment by stefanocke** [comment]
NPE originates here:

```
java.lang.NullPointerException
	at org.eclipse.xtext.xbase.lib.IterableExtensions.findFirst(IterableExtensions.java:81)
	at de.japkit.services.TypeElementFromCompilerCache.getTypeElement(TypeElementFromCompilerCache.java:62)
	at de.japkit.services.TypesRegistry.lambda$hasUnresolvedTypeDependencies$37(TypesRegistry.java:953)
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.exists(IteratorExtensions.java:267)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.exists(IterableExtensions.java:223)
	at de.japkit.services.TypesRegistry.hasUnresolvedTypeDependencies(TypesRegistry.java:966)
	at de.japkit.processor.JapkitProcessor.lambda$processLayerAsFarAsPossible$33(JapkitProcessor.java:499)
	at org.eclipse.xtext.xbase.lib.internal.BooleanFunctionDelegate.apply(BooleanFunctionDelegate.java:42)
	at com.google.common.collect.Iterators$5.computeNext(Iterators.java:637)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at com.google.common.collect.Iterators$5.computeNext(Iterators.java:635)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
	at com.google.common.collect.Iterators.addAll(Iterators.java:355)
	at com.google.common.collect.Iterables.addAll(Iterables.java:320)
	at com.google.common.collect.Sets.newLinkedHashSet(Sets.java:365)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.toSet(IterableExtensions.java:640)
	at de.japkit.processor.JapkitProcessor.filterLayer(JapkitProcessor.java:459)
	at de.japkit.processor.JapkitProcessor.processLayerAsFarAsPossible(JapkitProcessor.java:501)
	at de.japkit.processor.JapkitProcessor.processInternal(JapkitProcessor.java:272)
	at de.japkit.processor.JapkitProcessor.process(JapkitProcessor.java:199)
```
